// src/utils/note-descriptions.ts
// Descriptions FR des notes olfactives + mapping emoji par catégorie.

// ─── Emoji par catégorie olfactive ──────────────────────────

const CATEGORY_EMOJI: Record<string, string> = {
  citrus: '🍋',
  fruit: '🍎',
  spice: '🌶️',
  floral: '🌸',
  woody: '🪵',
  resin: '💧',
  musk: '🦌',
  green: '🌿',
  gourmand: '🍯',
  synthetic: '⚗️',
  alcohol: '🥃',
  leather: '👜',
  aquatic: '💧',
  powdery: '🌸',
};

const NOTE_CATEGORIES: Record<string, string> = {
  bergamot: 'citrus', 'sicilian bergamot': 'citrus', 'calabrian bergamot': 'citrus',
  lemon: 'citrus', 'italian lemon': 'citrus', 'sicilian lemon': 'citrus', 'californian lemon': 'citrus', 'amalfi lemon': 'citrus',
  grapefruit: 'citrus', 'mandarin orange': 'citrus', 'mandarin': 'citrus', 'italian mandarin': 'citrus', 'green mandarin': 'citrus',
  orange: 'citrus', 'bitter orange': 'citrus', 'blood orange': 'citrus', 'sicilian orange': 'citrus',
  tangerine: 'citrus', 'lime': 'citrus', 'citruses': 'citrus', 'citrus': 'citrus', 'sicilian citruses': 'citrus',
  yuzu: 'citrus', 'petitgrain': 'citrus',
  apple: 'fruit', 'green apple': 'fruit', 'pear': 'fruit', 'peach': 'fruit', 'white peach': 'fruit',
  apricot: 'fruit', 'blackberry': 'fruit', 'black currant': 'fruit', 'cassis': 'fruit',
  raspberry: 'fruit', 'strawberry': 'fruit', 'pineapple': 'fruit', 'plum': 'fruit', 'damask plum': 'fruit',
  litchi: 'fruit', 'cherry': 'fruit', 'coconut': 'fruit', 'mango': 'fruit', 'passionfruit': 'fruit',
  nectarine: 'fruit', 'cranberry': 'fruit', 'melon': 'fruit', 'boysenberry': 'fruit',
  'red berries': 'fruit', 'wild berries': 'fruit', 'berry fruits': 'fruit', 'grapes': 'fruit', 'watermelon': 'fruit',
  fig: 'fruit', 'rhubarb leaf': 'green',
  'pink pepper': 'spice', 'black pepper': 'spice', 'black and pink pepper': 'spice', 'pepper': 'spice', 'sichuan pepper': 'spice', 'green pepper': 'spice',
  saffron: 'spice', cardamom: 'spice', cardamon: 'spice', 'guatemalan cardamom': 'spice',
  cinnamon: 'spice', 'clove': 'spice', 'cloves': 'spice', nutmeg: 'spice', ginger: 'spice',
  caraway: 'spice', coriander: 'spice', cumin: 'spice', anise: 'spice', licorice: 'spice',
  'curry tree': 'spice', basil: 'spice', thyme: 'spice', 'red thyme': 'spice', sage: 'spice',
  'clary sage': 'spice', rosemary: 'spice', tarragon: 'spice', oregano: 'spice',
  'exotic spices': 'spice', 'bay leaf': 'spice',
  rose: 'floral', 'bulgarian rose': 'floral', 'turkish rose': 'floral', jasmine: 'floral',
  lavender: 'floral', iris: 'floral', 'white iris': 'floral', violet: 'floral',
  tuberose: 'floral', gardenia: 'floral', 'ylang-ylang': 'floral', neroli: 'floral',
  'orange blossom': 'floral', magnolia: 'floral', peony: 'floral', muguet: 'floral',
  'lily of the valley': 'floral', lily: 'floral', 'water lily': 'floral',
  freesia: 'floral', hyacinth: 'floral', narcissus: 'floral', orchid: 'floral',
  geranium: 'floral', heliotrope: 'floral', mimosa: 'floral', osmanthus: 'floral',
  chamomile: 'floral', honeysuckle: 'floral', 'floral notes': 'floral',
  cedar: 'woody', sandalwood: 'woody', vetiver: 'woody', patchouli: 'woody',
  oakmoss: 'woody', 'guaiac wood': 'woody', cypress: 'woody', pine: 'woody', fir: 'woody',
  birch: 'woody', ebony: 'woody', 'cashmere wood': 'woody', amberwood: 'woody',
  oud: 'woody', agarwood: 'woody', woods: 'woody',
  amber: 'resin', incense: 'resin', frankincense: 'resin', myrrh: 'resin',
  benzoin: 'resin', labdanum: 'resin', 'tolu balsam': 'resin', 'balsamic notes': 'resin',
  resins: 'resin', opoponax: 'resin', elemi: 'resin', styrax: 'resin',
  musk: 'musk', 'white musk': 'musk', 'ambrette (musk mallow)': 'musk', ambrette: 'musk',
  castoreum: 'musk', civet: 'musk', civetta: 'musk',
  leather: 'leather', suede: 'leather',
  'green notes': 'green', 'water notes': 'green', 'marine notes': 'green', 'sea salt': 'green',
  grass: 'green', galbanum: 'green', artemisia: 'green', wormwood: 'green',
  ivy: 'green', moss: 'green', oak: 'green', tea: 'green', 'green tea': 'green',
  mate: 'green', verbena: 'green', angelica: 'green', papyrus: 'green',
  vanilla: 'gourmand', vanila: 'gourmand', 'bourbon vanilla': 'gourmand', 'madagascar vanilla': 'gourmand',
  'vanilla bean': 'gourmand', 'vanilla sugar': 'gourmand', 'tonka bean': 'gourmand',
  caramel: 'gourmand', chocolate: 'gourmand', cocoa: 'gourmand', cacao: 'gourmand',
  honey: 'gourmand', 'white honey': 'gourmand', almond: 'gourmand', 'bitter almond': 'gourmand',
  'sweet almond': 'gourmand', 'almond milk': 'gourmand', praline: 'gourmand',
  coffee: 'gourmand', 'roasted coffee beans': 'gourmand', chestnut: 'gourmand',
  hazelnut: 'gourmand', marshmallow: 'gourmand', 'cotton candy': 'gourmand',
  sugar: 'gourmand', 'brown sugar': 'gourmand', lactonic: 'gourmand', milk: 'gourmand',
  'ice cream': 'gourmand', popcorn: 'gourmand', carrot: 'gourmand',
  ambroxan: 'synthetic', 'iso e super': 'synthetic', hedione: 'synthetic',
  cashmeran: 'synthetic', norlimbanol: 'synthetic', sylkolide: 'synthetic',
  mahonial: 'synthetic', pomarose: 'synthetic', 'belambra tree': 'synthetic', calone: 'synthetic',
  cannabis: 'alcohol', rum: 'alcohol', whiskey: 'alcohol', gin: 'alcohol',
  cognac: 'alcohol', tobacco: 'alcohol', smoke: 'alcohol',
  powder: 'powdery', aldehydes: 'synthetic', ozonic: 'synthetic',
  mineral: 'green', 'earthy notes': 'green', spices: 'spice', acacia: 'floral',
  'melon or sweet clover': 'green',
};

// ─── Descriptions ───────────────────────────────────────────

const NOTE_DESCRIPTIONS: Record<string, string> = {
  // Agrumes
  bergamot: 'Agrume méditerranéen au parfum frais, acidulé et légèrement floral. Incontournable des eaux de Cologne.',
  'sicilian bergamot': 'Variété de bergamote cultivée en Sicile, réputée pour sa fraîcheur éclatante et sa rondeur.',
  'calabrian bergamot': 'Bergamote de Calabre, la plus fameuse. Son huile essentielle offre un départ pétillant aux notes vertes.',
  lemon: 'Note vive et acidulée qui apporte une fraîcheur immédiate. Souvent utilisé en note de tête pour un effet tonique.',
  'italian lemon': 'Citron d\'Italie, juteux et ensoleillé. Apporte une luminosité incomparable aux compositions.',
  'sicilian lemon': 'Citron sicilien intense, entre acidité mordante et douceur zestée. Signature de nombreux parfums d\'été.',
  grapefruit: 'Agrume tonique au caractère amer et pétillant. Donne du mordant aux compositions masculines et mixtes.',
  'mandarin orange': 'Agrume doux, rond et juteux. Apporte une fraîcheur fruitée moins acide que le citron.',
  mandarin: 'Note fruitée et ensoleillée, douce et légèrement sucrée. Très utilisée dans les parfums hespéridés.',
  'green mandarin': 'Mandarine verte, plus vive et acidulée que la mandarine mûre. Apporte peps et verdeur.',
  orange: 'Fruit juteux et solaire, entre douceur et vivacité. Évoque la Méditerranée.',
  'bitter orange': 'Orange amère, plus complexe que l\'orange douce, avec une facette verte et légèrement boisée.',
  'blood orange': 'Orange sanguine au parfum intense, entre acidité framboisée et douceur fruitée.',
  tangerine: 'Petite mandarine sucrée et juteuse. Apporte une rondeur fruitée et lumineuse.',
  lime: 'Citron vert au caractère vif, exotique et pétillant. Plus acide que le citron jaune.',
  citruses: 'Famille des agrumes : fraîcheur, vitalité, pétillance. Base de la famille hespéridée en parfumerie.',
  yuzu: 'Agrume japonais entre citron, mandarine et pamplemousse. Très prisé pour son élégance aromatique.',
  petitgrain: 'Distillat de feuilles et rameaux d\'oranger amer. Note fraîche, verte et légèrement florale.',
  // Fruits
  apple: 'Note fruitée croquante, entre fraîcheur verte et douceur sucrée. Apporte du pep et de la jeunesse.',
  'green apple': 'Pomme verte acidulée et juteuse. Fraîcheur fruitée immédiate et tonique.',
  pear: 'Fruit juteux à la douceur veloutée. Apporte une rondeur fruitée élégante sans être sucrée.',
  peach: 'Fruit charnu au parfum velouté, entre douceur sucrée et acidité légère. Note sensuelle et solaire.',
  'white peach': 'Pêche blanche délicate et aérienne. Plus subtile que la pêche jaune, presque lactée.',
  apricot: 'Fruit solaire à la chair tendre, entre acidité douce et sucrosité. Apporte une facette fruitée chaleureuse.',
  blackberry: 'Baie noire juteuse et intense. Apporte une facette fruitée sombre et légèrement boisée.',
  'black currant': 'Cassis au caractère puissant, entre acidité verte et profondeur fruitée. Très présent en parfumerie.',
  raspberry: 'Framboise vive et acidulée. Note fruitée pétillante, souvent utilisée dans les compositions modernes.',
  strawberry: 'Fraise sucrée et juteuse. Plutôt rare en parfumerie fine, elle apporte une touche gourmande et enfantine.',
  pineapple: 'Fruit exotique juteux, entre acidité et sucre. Apporte du soleil et de l\'exotisme.',
  plum: 'Prune à la chair sucrée et légèrement épicée. Note fruitée sombre et profonde.',
  litchi: 'Fruit exotique délicat au parfum de rose et de muscat. Très aérien et sophistiqué.',
  cherry: 'Cerise juteuse entre douceur et acidité. Peut être fruitée, amandée ou légèrement alcoolisée.',
  coconut: 'Fruit exotique crémeux et lacté. Évoque les vacances, le soleil et les peaux hâlées.',
  mango: 'Fruit tropical à la chair onctueuse, entre douceur sucrée et pointe acidulée.',
  passionfruit: 'Fruit de la passion exotique, vif et acidulé. Apporte une touche tropicale pétillante.',
  melon: 'Fruit aqueux et rafraîchissant, légèrement sucré. Apporte une sensation de fraîcheur estivale.',
  'red berries': 'Mélange de fruits rouges acidulés. Fraîcheur fruitée vive et dynamique.',
  'wild berries': 'Baies sauvages au caractère plus brut et intense que les fruits rouges classiques.',
  fig: 'Fruit méditerranéen à la sève laiteuse et verte. Entre fruité, boisé et lacté — très élégant.',
  // Épicés
  'pink pepper': 'Baie rose au caractère vif, frais et légèrement floral. Piquant plus subtil que le poivre noir.',
  'black pepper': 'Épice au piquant sec et boisé. Apporte du caractère et de la profondeur aux compositions.',
  saffron: 'Épice la plus précieuse au monde. Parfum chaud, cuiré et légèrement amer, signature orientale.',
  cardamom: 'Épice aromatique fraîche, entre eucalyptus et citronnelle. Apporte un souffle vert et épicé.',
  cinnamon: 'Épice chaude et réconfortante au parfum sucré-boisé. Incontournable des orientaux et des gourmands.',
  'clove': 'Clou de girofle au parfum puissant, chaud et camphré. Apporte une facette épicée intense.',
  nutmeg: 'Noix de muscade chaude et légèrement boisée. Plus subtile que le girofle, elle adoucit les épices.',
  ginger: 'Rhizome au piquant frais, citronné et épicé. Apporte du pep et une sensation tonique.',
  coriander: 'Graine à la facette aromatique fraîche et légèrement florale. Très utilisée dans les fougères.',
  cumin: 'Épice au caractère puissant et animal. Très chaud, presque transpirant — à doser avec parcimonie.',
  anise: 'Graine au goût de réglisse frais et sucré. Apporte une facette herbacée et douce.',
  licorice: 'Note sucrée, herbacée et légèrement boisée. Apporte rondeur et originalité.',
  // Floraux
  rose: 'Reine des fleurs en parfumerie. Peut être fraîche et verte, fruitée, miellée, ou sombre et épicée.',
  'bulgarian rose': 'Rose de Bulgarie, la plus réputée. Parfum riche, profond et légèrement miellé.',
  jasmine: 'Fleur blanche enivrante au parfum animal et solaire. Une des matières les plus précieuses de la parfumerie.',
  lavender: 'Plante aromatique fraîche, camphrée et herbacée. Emblématique des fougères masculines.',
  iris: 'Racine noble au parfum poudré, beurré et terreux. L\'un des ingrédients les plus chers de la parfumerie.',
  violet: 'Petite fleur au parfum poudré, délicat et légèrement sucré. Très élégante et rétro.',
  tuberose: 'Fleur blanche capiteuse au parfum crémeux, vert et presque camphré. Extrêmement puissante et sensuelle.',
  'orange blossom': 'Fleur d\'oranger au parfum solaire, miellé et légèrement indolé. Évoque la Méditerranée.',
  neroli: 'Essence de fleur d\'oranger amer. Plus frais et vert que l\'orange blossom, très lumineux.',
  'ylang-ylang': 'Fleur exotique au parfum solaire, banané et légèrement épicé. Très sensuelle, emblème des orientaux.',
  magnolia: 'Fleur à la fois fraîche (citronnée) et crémeuse. Élégance printanière entre floral et fruité.',
  peony: 'Pivoine au parfum de rose fraîche et de fruits rouges. Féminine, aérienne et romantique.',
  'lily of the valley': 'Muguet frais, vert et légèrement aquatique. Symbole du printemps. Le muguet naturel est impossible à extraire.',
  osmanthus: 'Petite fleur chinoise au parfum d\'abricot et de cuir souple. Très sophistiquée et rare.',
  // Boisés
  cedar: 'Bois sec, élégant et minéral. Apporte structure et verticalité aux compositions.',
  sandalwood: 'Bois crémeux et lacté au parfum doux et persistant. Originaire d\'Inde, très précieux et apaisant.',
  vetiver: 'Racine boisée, terreuse et fumée. Entre fraîcheur verte et profondeur sombre — très masculin.',
  patchouli: 'Plante au parfum boisé, terreux et camphré. Icône des années hippies, aujourd\'hui symbole de sensualité.',
  oakmoss: 'Lichen poussant sur les chênes. Parfum de sous-bois humide, terreux et légèrement salé. Base des chypres.',
  'guaiac wood': 'Bois de gaïac au parfum fumé, goudronné et légèrement vanillé. Très chaud et enveloppant.',
  cypress: 'Conifère méditerranéen au parfum vert et résineux. Apporte une fraîcheur boisée élégante.',
  oud: 'Bois d\'agar infecté par un champignon. Parfum animal, boisé et cuiré, extrêmement puissant. « L\'or noir » de la parfumerie.',
  'cashmere wood': 'Note de synthèse évoquant un bois doux, musqué et légèrement épicé. Enveloppant comme un cachemire.',
  amberwood: 'Bois ambré moderne, entre bois sec et ambre chaud. Très utilisé dans les parfums contemporains.',
  // Résines & Baumes
  amber: 'Accord chaud et réconfortant, mêlant vanille, résines et baumes. Note de fond sensuelle et enveloppante.',
  incense: 'Résine brûlée au parfum fumé, mystique et épicé. Évoque les églises et les temples.',
  frankincense: 'Oliban, résine sacrée au parfum citronné, fumé et balsamique. Utilisée depuis l\'Antiquité.',
  myrrh: 'Résine sombre au parfum balsamique, légèrement amer et médicinal. Plus sombre que l\'oliban.',
  benzoin: 'Résine douce au parfum de vanille chaude et de caramel. Très réconfortante, presque gourmande.',
  labdanum: 'Résine du ciste, au parfum ambré, cuiré et animal. Base essentielle des parfums orientaux et chyprés.',
  // Muscs & Cuir
  musk: 'Note animale, chaude et sensuelle. Les muscs modernes sont synthétiques : blancs (doux), ou plus sombres.',
  'white musk': 'Musc synthétique doux, propre et cotonneux. Donne une sensation de propreté et de réconfort.',
  ambrette: 'Graine végétale au parfum musqué, floral et légèrement boisé. Alternative naturelle aux muscs animaux.',
  leather: 'Accord cuir au caractère animal, fumé et sec. Évoque le cuir de sellerie, puissant et élégant.',
  suede: 'Cuir souple et velouté, plus doux que le cuir classique. Apporte une facette animale raffinée.',
  // Verts & Aquatiques
  'green notes': 'Notes vertes évoquant l\'herbe fraîche, les feuilles froissées, la sève. Fraîcheur naturelle et végétale.',
  'marine notes': 'Accord aquatique évoquant l\'air marin, les embruns et les algues. Fraîcheur iodée.',
  'water notes': 'Notes aquatiques synthétiques évoquant l\'eau fraîche, la pastèque et le calone. Très années 90.',
  'sea salt': 'Sel marin apportant une facette minérale, iodée et salée. Fraîcheur océanique immédiate.',
  grass: 'Herbe coupée au parfum vert vif et légèrement amer. Fraîcheur printanière instantanée.',
  'green tea': 'Thé vert délicat, entre fraîcheur herbacée et douceur légèrement amère. Zen et apaisant.',
  mate: 'Plante sud-américaine au parfum herbacé, fumé et légèrement amer. Énergisant et original.',
  verbena: 'Verveine citronnée, fraîche et légèrement sucrée. Parfum de jardin en été.',
  // Gourmands
  vanilla: 'Gousse sucrée, chaude et réconfortante. Une des notes les plus populaires au monde.',
  'bourbon vanilla': 'Vanille Bourbon de Madagascar ou La Réunion. Plus riche, plus animale et plus complexe que la vanille standard.',
  'tonka bean': 'Fève au parfum entre vanille, amande amère et tabac. Chaud, sucré et addictif.',
  caramel: 'Note sucrée et chaleureuse de sucre cuit. Évoque la pâtisserie et le réconfort.',
  chocolate: 'Note gourmande sombre et addictive. Peut être noir, lacté ou poudré selon le traitement.',
  honey: 'Miel au parfum sucré, floral et légèrement animal. Apporte rondeur et sensualité.',
  almond: 'Amande douce, entre fruité et légèrement amer. Très utilisée dans les notes de fond gourmandes.',
  praline: 'Mélange de caramel et d\'amande torréfiée. Gourmandise pure, très addictive.',
  coffee: 'Grain torréfié au parfum sombre, amer et chaleureux. Apporte du caractère et une facette de torréfaction.',
  hazelnut: 'Noisette torréfiée, entre bois sec et douceur gourmande. Plus subtile que l\'amande.',
  marshmallow: 'Guimauve sucrée et aérienne. Apporte une rondeur douce et cotonneuse, enfantine.',
  // Synthétiques
  ambroxan: 'Molécule de synthèse évoquant l\'ambre gris (ambre gris naturel). Parfum minéral, boisé et musqué. Très diffusif.',
  'iso e super': 'Molécule boisée et ambrée au parfum velouté. Apporte un halo diffus et addictif. Présent dans des centaines de parfums.',
  cashmeran: 'Molécule aux facettes boisées, musquées et épicées. Évoque la douceur du cachemire. Très enveloppante.',
  hedione: 'Molécule au parfum de jasmin aérien et frais. Apporte de la légèreté et de la transparence aux compositions.',
  aldehydes: 'Molécules de synthèse au parfum métallique, ciré et pétillant. Icônes de la parfumerie moderne (Chanel N°5).',
  // Alcooliques & Tabac
  tobacco: 'Note chaleureuse de tabac blond ou brun. Peut être miellé, fumé ou fruité selon le traitement.',
  rum: 'Alcool chaud au parfum sucré, boisé et légèrement épicé. Apporte une facette caraïbéenne et sensuelle.',
  whiskey: 'Alcool noble au parfum boisé, fumé et vanillé. Évoque les fûts de chêne et le malt.',
  cognac: 'Eau-de-vie raffinée au parfum de fruits confits, de vanille et de chêne. Luxe et élégance.',
  gin: 'Alcool aromatique au genièvre, frais et herbacé. Apporte une facette aromatique et pétillante.',
  smoke: 'Note fumée évoquant le bois brûlé, la fumée de cheminée. Apporte du caractère et une facette sombre.',
  // Divers
  powder: 'Accord poudré évoquant le talc, le riz, le maquillage vintage. Très élégant et réconfortant.',
  ozonic: 'Note de synthèse évoquant l\'air frais après l\'orage, presque électrique. Apporte de la légèreté.',
  mineral: 'Note minérale évoquant la pierre chauffée, la craie ou le silex. Facette sèche et austère.',
  'earthy notes': 'Notes terreuses évoquant le sous-bois, la terre humide ou le géosmine. Profondes et sombres.',
  oak: 'Bois de chêne au parfum sec, noble et légèrement fumé. Apporte structure et longévité.',
  moss: 'Mousse végétale au parfum de sous-bois, humide et vert. Base des parfums chyprés.',
};

// ─── Fonctions publiques ─────────────────────────────────────

/** Retourne l'emoji associé à une note, basé sur sa catégorie olfactive. */
export function getNoteEmoji(noteName: string): string {
  const key = noteName.toLowerCase().trim();
  const category = NOTE_CATEGORIES[key];
  return category ? (CATEGORY_EMOJI[category] ?? '✨') : '✨';
}

/** Retourne la description FR d'une note olfactive. Fallback générique si inconnue. */
export function getNoteDescription(noteName: string): string {
  const key = noteName.toLowerCase().trim();
  const desc = NOTE_DESCRIPTIONS[key];
  if (desc) return desc;
  return 'Une matière première ou un accord utilisé en parfumerie pour apporter une facette olfactive spécifique à la composition.';
}
