// src/models/perfumes-seed.ts — Part 1/2

import type { Parfum } from './parfum.interface';

export const PERFUMES_SEED: Omit<Parfum, 'id' | 'createdAt' | 'updatedAt'>[] = [
  { nom: 'N°5', marque: 'Chanel', annee: 1921, familleOlactive: 'Aldéhydé Floral', notesTete: ['Aldéhydes', 'Ylang-Ylang', 'Néroli', 'Citron', 'Bergamote'], notesCoeur: ['Iris', 'Jasmin', 'Rose de Mai', 'Muguet'], notesFond: ['Vétiver', 'Santal', 'Vanille', 'Ambre', 'Patchouli'], referencePrice: 105, bestPrice: 78 },
  { nom: "J'adore", marque: 'Dior', annee: 1999, familleOlactive: 'Floral Fruité', notesTete: ['Mandarine', 'Melon', 'Pêche', 'Poire', 'Magnolia'], notesCoeur: ['Jasmin', 'Rose', 'Violette', 'Freesia', 'Orchidée'], notesFond: ['Cèdre', 'Musc', 'Mûre', 'Vanille'], referencePrice: 102, bestPrice: 74 },
  { nom: 'Black Opium', marque: 'Yves Saint Laurent', annee: 2014, familleOlactive: 'Oriental Vanillé', notesTete: ['Poivre Rose', "Fleur d'Oranger", 'Poire'], notesCoeur: ['Café', 'Jasmin', 'Amande Amère', 'Réglisse'], notesFond: ['Vanille', 'Cèdre', 'Patchouli', 'Cachemire'], referencePrice: 92, bestPrice: 64 },
  { nom: 'Shalimar', marque: 'Guerlain', annee: 1925, familleOlactive: 'Oriental Ambré', notesTete: ['Bergamote', 'Citron', 'Mandarine', 'Cèdre'], notesCoeur: ['Jasmin', 'Rose', 'Iris', 'Patchouli'], notesFond: ['Vanille', 'Ambre', 'Fève Tonka', 'Musc', 'Cuir'], referencePrice: 86, bestPrice: 61 },
  { nom: 'La Vie Est Belle', marque: 'Lancôme', annee: 2012, familleOlactive: 'Floral Fruité', notesTete: ['Cassis', 'Poire'], notesCoeur: ['Iris', 'Jasmin', "Fleur d'Oranger"], notesFond: ['Patchouli', 'Vanille', 'Praliné', 'Fève Tonka'], referencePrice: 89, bestPrice: 66 },
  { nom: 'Le Male', marque: 'Jean Paul Gaultier', annee: 1995, familleOlactive: 'Fougère Oriental', notesTete: ['Menthe', 'Lavande', 'Cardamome', 'Bergamote'], notesCoeur: ['Cannelle', 'Cumin', "Fleur d'Oranger"], notesFond: ['Vanille', 'Santal', 'Fève Tonka', 'Ambre', 'Cèdre'], referencePrice: 75, bestPrice: 52 },
  { nom: 'Sauvage', marque: 'Dior', annee: 2015, familleOlactive: 'Aromatique Frais', notesTete: ['Bergamote de Calabre', 'Poivre du Sichuan'], notesCoeur: ['Lavande', 'Géranium', 'Poivre Rose', 'Vétiver'], notesFond: ['Ambroxan', 'Cèdre', 'Labdanum'], referencePrice: 98, bestPrice: 73 },
  { nom: 'Acqua di Giò', marque: 'Giorgio Armani', annee: 1996, familleOlactive: 'Aromatique Aquatique', notesTete: ['Citron', 'Bergamote', 'Néroli', 'Mandarine'], notesCoeur: ['Notes Marines', 'Jasmin', 'Pivoine', 'Coriandre'], notesFond: ['Cèdre', 'Musc', 'Patchouli', 'Mousse de Chêne'], referencePrice: 79, bestPrice: 56 },
  { nom: '1 Million', marque: 'Paco Rabanne', annee: 2008, familleOlactive: 'Boisé Épicé', notesTete: ['Pamplemousse', 'Menthe', 'Mandarine'], notesCoeur: ['Rose', 'Cannelle', 'Notes Épicées'], notesFond: ['Cuir', 'Ambre', 'Patchouli', 'Bois de Gaïac'], referencePrice: 78, bestPrice: 54 },
  { nom: "L'Interdit", marque: 'Givenchy', annee: 2018, familleOlactive: 'Floral Boisé', notesTete: ['Poire', 'Bergamote'], notesCoeur: ["Fleur d'Oranger", 'Jasmin', 'Tubéreuse'], notesFond: ['Patchouli', 'Vétiver', 'Vanille'], referencePrice: 98, bestPrice: 72 },
  { nom: 'Flowerbomb', marque: 'Viktor & Rolf', annee: 2005, familleOlactive: 'Oriental Floral', notesTete: ['Thé', 'Bergamote'], notesCoeur: ['Jasmin', "Fleur d'Oranger", 'Freesia', 'Orchidée', 'Rose'], notesFond: ['Patchouli', 'Vanille', 'Ambre', 'Musc'], referencePrice: 86, bestPrice: 59 },
  { nom: 'Coco Mademoiselle', marque: 'Chanel', annee: 2001, familleOlactive: 'Oriental Floral', notesTete: ['Orange', 'Bergamote', 'Mandarine'], notesCoeur: ['Rose', 'Jasmin', 'Mimosa', 'Ylang-Ylang'], notesFond: ['Patchouli', 'Vétiver', 'Vanille', 'Musc Blanc', 'Fève Tonka'], referencePrice: 110, bestPrice: 87 },
  { nom: 'Angel', marque: 'Thierry Mugler', annee: 1992, familleOlactive: 'Oriental Gourmand', notesTete: ['Cassis', 'Melon', 'Noix de Coco', 'Mandarine'], notesCoeur: ['Miel', 'Abricot', 'Mûre', 'Pêche', 'Jasmin'], notesFond: ['Chocolat', 'Vanille', 'Patchouli', 'Caramel', 'Musc'], referencePrice: 84, bestPrice: 60 },
  { nom: 'CK One', marque: 'Calvin Klein', annee: 1994, familleOlactive: 'Agrumes Aromatique', notesTete: ['Bergamote', 'Citron', 'Mandarine', 'Ananas', 'Cardamome'], notesCoeur: ['Violette', 'Rose', 'Noix de Muscade', 'Jasmin'], notesFond: ['Musc', 'Ambre', 'Cèdre', 'Mousse de Chêne'], referencePrice: 52, bestPrice: 34 },
  { nom: 'Light Blue', marque: 'Dolce & Gabbana', annee: 2001, familleOlactive: 'Floral Fruité', notesTete: ['Citron', 'Pomme Granny Smith', 'Cèdre'], notesCoeur: ['Jasmin', 'Rose Blanche', 'Bambou'], notesFond: ['Musc', 'Ambre', 'Bois de Cèdre'], referencePrice: 68, bestPrice: 47 },
  { nom: "La Nuit de L'Homme", marque: 'Yves Saint Laurent', annee: 2009, familleOlactive: 'Oriental Épicé', notesTete: ['Cardamome', 'Bergamote'], notesCoeur: ['Lavande', 'Cèdre', 'Cumin'], notesFond: ['Vétiver', 'Fève Tonka', 'Carvi'], referencePrice: 84, bestPrice: 62 },
  { nom: 'Black Orchid', marque: 'Tom Ford', annee: 2006, familleOlactive: 'Oriental Floral', notesTete: ['Truffe', 'Gardénia', 'Cassis', 'Ylang-Ylang'], notesCoeur: ['Orchidée Noire', 'Fleur de Lotus', 'Notes Épicées'], notesFond: ['Patchouli', 'Ambre', 'Vanille', 'Santal', 'Chocolat Noir'], referencePrice: 128, bestPrice: 94 },
  { nom: 'La Petite Robe Noire', marque: 'Guerlain', annee: 2012, familleOlactive: 'Floral Fruité', notesTete: ['Cerise', 'Amande', 'Bergamote', 'Baies Rouges'], notesCoeur: ['Rose', 'Réglisse', "Fleur d'Oranger"], notesFond: ['Vanille', 'Patchouli', 'Iris', 'Fève Tonka'], referencePrice: 82, bestPrice: 58 },
  { nom: 'Lady Million', marque: 'Paco Rabanne', annee: 2010, familleOlactive: 'Floral Boisé', notesTete: ['Néroli', 'Framboise', "Fleur d'Oranger"], notesCoeur: ['Jasmin', "Fleur d'Oranger", 'Gardénia'], notesFond: ['Patchouli', 'Miel', 'Ambre'], referencePrice: 76, bestPrice: 52 },
  { nom: 'Aventus', marque: 'Creed', annee: 2010, familleOlactive: 'Fruité Boisé', notesTete: ['Ananas', 'Pomme', 'Bergamote', 'Cassis'], notesCoeur: ['Bouleau', 'Patchouli', 'Jasmin', 'Rose'], notesFond: ['Musc', 'Mousse de Chêne', 'Ambre Gris', 'Vanille'], referencePrice: 285, bestPrice: 219 },
  { nom: 'Naxos', marque: 'Xerjoff', annee: 2015, familleOlactive: 'Oriental Épicé', notesTete: ['Bergamote', 'Citron', 'Lavande'], notesCoeur: ['Cannelle', 'Miel', 'Jasmin'], notesFond: ['Tabac', 'Vanille', 'Fève Tonka'], referencePrice: 245, bestPrice: 189 },
];